using System.Collections.Generic;

namespace UltraVideoEditor
{
    public static class LanguageManager
    {
        private static Dictionary<string, Dictionary<string, string>> _translations;

        static LanguageManager()
        {
            _translations = new Dictionary<string, Dictionary<string, string>>();

            // ==================== SRPSKI ====================
            var sr = new Dictionary<string, string>();
            sr["app_title"] = "ULTRA VIDEO EDITOR v1.0";
            sr["system_ready"] = "Sistem spreman...";
            sr["status_idle"] = "Status: Idle";
            sr["save_project"] = "Sačuvaj projekat";
            sr["load_project"] = "Učitaj projekat";
            sr["accessibility"] = "Pristupačni mod";
            sr["help"] = "Pomoć";
            sr["play"] = "PLAY";
            sr["pause"] = "PAUSE";
            sr["render"] = "RENDER";
            sr["add_video"] = "Dodaj video";
            sr["add_audio"] = "Dodaj audio";
            sr["add_video_track"] = "Dodaj video traku";
            sr["add_audio_track"] = "Dodaj audio traku";
            sr["delete"] = "Obriši";
            sr["cut"] = "Seci";
            sr["cut_all_markers"] = "Seci na svim markerima";
            sr["duration"] = "Trajanje";
            sr["volume"] = "Jačina zvuka";
            sr["zoom_in"] = "Uvećaj zoom";
            sr["zoom_out"] = "Smanji zoom";
            sr["marker"] = "Dodaj marker";
            sr["next_marker"] = "Sledeći marker";
            sr["prev_marker"] = "Prethodni marker";
            sr["move_left"] = "Pomeri levo";
            sr["move_right"] = "Pomeri desno";
            sr["seek_back"] = "Premotaj unazad 5s";
            sr["seek_forward"] = "Premotaj napred 5s";
            sr["gpu_acceleration"] = "GPU ubrzanje";
            sr["timeline_tab"] = "TIMELINE";
            sr["ai_tab"] = "AI FUNKCIJE";
            sr["effects_tab"] = "EFEKTI";
            sr["subtitles_tab"] = "TITLOVI";
            sr["transitions_tab"] = "TRANZICIJE";
            sr["animation_tab"] = "ANIMACIJE";
            sr["ai_voice"] = "AI GLAS";
            sr["ai_frames"] = "AI KADROVI";
            sr["ai_lyrics"] = "AI SINHRONIZACIJA";
            sr["ai_transcribe"] = "AI TRANSKRIPCIJA";
            sr["generate_voice"] = "Generiši glas";
            sr["generate_frames"] = "Generiši kadrove";
            sr["sync_lyrics"] = "Sinhronizuj tekst";
            sr["add_subtitles"] = "Dodaj titlove";
            sr["voice_text"] = "Tekst za govor:";
            sr["lyrics_text"] = "Tekst pesme:";
            sr["select_audio"] = "Selektuj audio:";
            sr["ai_prompt"] = "Opis slike (odvoji zarezom):";
            sr["transcribe_label"] = "Audio fajl za transkripciju:";
            sr["transcribe_button"] = "Transkribuj";
            sr["transcription_result"] = "Rezultat transkripcije";
            sr["video_effects"] = "VIDEO EFEKTI";
            sr["audio_effects"] = "AUDIO EFEKTI";
            sr["brightness"] = "Svetlina:";
            sr["contrast"] = "Kontrast:";
            sr["blur"] = "Zamagljenje:";
            sr["bass"] = "Bas:";
            sr["treble"] = "Treble:";
            sr["reverb"] = "Reverb:";
            sr["compressor"] = "Kompresor";
            sr["apply_effects"] = "Primeni efekte";
            sr["subtitle_text"] = "Tekst titla:";
            sr["subtitle_start"] = "Početak (s):";
            sr["subtitle_end"] = "Kraj (s):";
            sr["add_subtitle"] = "Dodaj titl";
            sr["clear_subtitles"] = "Obriši sve titlove";
            sr["export_options"] = "Opcije izvoza";
            sr["select_clip_first"] = "Selektuj klip prvo";
            sr["save_project_first"] = "Prvo sačuvaj projekat!";
            sr["no_clips_to_render"] = "Nema klipova za render";
            sr["render_complete"] = "Render završen";
            sr["render_complete_message"] = "Video je renderovan!";
            sr["render_failed"] = "Renderovanje nije uspelo!";
            sr["render_cancelled"] = "Renderovanje otkazano";
            sr["rendering"] = "Renderovanje...";
            sr["done"] = "Završeno";
            sr["undo"] = "Poništeno";
            sr["redo"] = "Ponovljeno";
            sr["no_more_undo"] = "Nema više za poništavanje";
            sr["no_more_redo"] = "Nema više za ponavljanje";
            sr["project_saved"] = "Projekat sačuvan";
            sr["project_loaded"] = "Projekat učitan";
            sr["new_project"] = "Novi";
            sr["open_project"] = "Otvori";
            sr["copy"] = "Kopiraj";
            sr["paste"] = "Zalepi";
            _translations["sr"] = sr;

            // ==================== ENGLISH ====================
            var en = new Dictionary<string, string>();
            en["app_title"] = "ULTRA VIDEO EDITOR v1.0";
            en["system_ready"] = "System ready...";
            en["status_idle"] = "Status: Idle";
            en["save_project"] = "Save project";
            en["load_project"] = "Load project";
            en["accessibility"] = "Accessibility mode";
            en["help"] = "Help";
            en["play"] = "PLAY";
            en["pause"] = "PAUSE";
            en["render"] = "RENDER";
            en["add_video"] = "Add video";
            en["add_audio"] = "Add audio";
            en["add_video_track"] = "Add video track";
            en["add_audio_track"] = "Add audio track";
            en["delete"] = "Delete";
            en["cut"] = "Cut";
            en["cut_all_markers"] = "Cut at all markers";
            en["duration"] = "Duration";
            en["volume"] = "Volume";
            en["zoom_in"] = "Zoom in";
            en["zoom_out"] = "Zoom out";
            en["marker"] = "Add marker";
            en["next_marker"] = "Next marker";
            en["prev_marker"] = "Previous marker";
            en["move_left"] = "Move left";
            en["move_right"] = "Move right";
            en["seek_back"] = "Seek back 5s";
            en["seek_forward"] = "Seek forward 5s";
            en["gpu_acceleration"] = "GPU acceleration";
            en["timeline_tab"] = "TIMELINE";
            en["ai_tab"] = "AI FUNCTIONS";
            en["effects_tab"] = "EFFECTS";
            en["subtitles_tab"] = "SUBTITLES";
            en["transitions_tab"] = "TRANSITIONS";
            en["animation_tab"] = "ANIMATION";
            en["ai_voice"] = "AI VOICE";
            en["ai_frames"] = "AI FRAMES";
            en["ai_lyrics"] = "AI SYNC";
            en["ai_transcribe"] = "AI TRANSCRIPTION";
            en["generate_voice"] = "Generate voice";
            en["generate_frames"] = "Generate frames";
            en["sync_lyrics"] = "Sync lyrics";
            en["add_subtitles"] = "Add subtitles";
            en["voice_text"] = "Text to speak:";
            en["lyrics_text"] = "Lyrics:";
            en["select_audio"] = "Select audio:";
            en["ai_prompt"] = "Image description (comma separated):";
            en["transcribe_label"] = "Audio file for transcription:";
            en["transcribe_button"] = "Transcribe";
            en["transcription_result"] = "Transcription result";
            en["video_effects"] = "VIDEO EFFECTS";
            en["audio_effects"] = "AUDIO EFFECTS";
            en["brightness"] = "Brightness:";
            en["contrast"] = "Contrast:";
            en["blur"] = "Blur:";
            en["bass"] = "Bass:";
            en["treble"] = "Treble:";
            en["reverb"] = "Reverb:";
            en["compressor"] = "Compressor";
            en["apply_effects"] = "Apply effects";
            en["subtitle_text"] = "Subtitle text:";
            en["subtitle_start"] = "Start (s):";
            en["subtitle_end"] = "End (s):";
            en["add_subtitle"] = "Add subtitle";
            en["clear_subtitles"] = "Clear all subtitles";
            en["export_options"] = "Export options";
            en["select_clip_first"] = "Select a clip first";
            en["save_project_first"] = "Save project first!";
            en["no_clips_to_render"] = "No clips to render";
            en["render_complete"] = "Render complete";
            en["render_complete_message"] = "Video rendered!";
            en["render_failed"] = "Render failed!";
            en["render_cancelled"] = "Render cancelled";
            en["rendering"] = "Rendering...";
            en["done"] = "Done";
            en["undo"] = "Undo";
            en["redo"] = "Redo";
            en["no_more_undo"] = "No more actions to undo";
            en["no_more_redo"] = "No more actions to redo";
            en["project_saved"] = "Project saved";
            en["project_loaded"] = "Project loaded";
            en["new_project"] = "New";
            en["open_project"] = "Open";
            en["copy"] = "Copy";
            en["paste"] = "Paste";
            _translations["en"] = en;

            // ==================== NEMAČKI ====================
            var de = new Dictionary<string, string>();
            de["app_title"] = "ULTRA VIDEO EDITOR v1.0";
            de["system_ready"] = "System bereit...";
            de["status_idle"] = "Status: Bereit";
            de["save_project"] = "Projekt speichern";
            de["load_project"] = "Projekt laden";
            de["accessibility"] = "Barrierefreiheit";
            de["help"] = "Hilfe";
            de["play"] = "PLAY";
            de["pause"] = "PAUSE";
            de["render"] = "RENDERN";
            de["add_video"] = "Video hinzufügen";
            de["add_audio"] = "Audio hinzufügen";
            de["delete"] = "Löschen";
            de["cut"] = "Schneiden";
            de["duration"] = "Dauer";
            de["volume"] = "Lautstärke";
            de["zoom_in"] = "Vergrößern";
            de["zoom_out"] = "Verkleinern";
            de["marker"] = "Markierung hinzufügen";
            de["next_marker"] = "Nächste Markierung";
            de["prev_marker"] = "Vorherige Markierung";
            de["move_left"] = "Nach links";
            de["move_right"] = "Nach rechts";
            de["seek_back"] = "5s zurück";
            de["seek_forward"] = "5s vor";
            de["gpu_acceleration"] = "GPU Beschleunigung";
            de["timeline_tab"] = "ZEITLEISTE";
            de["ai_tab"] = "KI FUNKTIONEN";
            de["effects_tab"] = "EFFEKTE";
            de["subtitles_tab"] = "UNTERTITEL";
            de["select_clip_first"] = "Wählen Sie zuerst einen Clip aus";
            de["save_project_first"] = "Speichern Sie zuerst das Projekt!";
            de["no_clips_to_render"] = "Keine Clips zum Rendern";
            de["render_complete"] = "Rendern abgeschlossen";
            de["render_complete_message"] = "Video wurde gerendert!";
            de["render_failed"] = "Rendern fehlgeschlagen!";
            de["rendering"] = "Rendern...";
            de["done"] = "Fertig";
            de["undo"] = "Rückgängig";
            de["redo"] = "Wiederholen";
            de["project_saved"] = "Projekt gespeichert";
            de["project_loaded"] = "Projekt geladen";
            de["new_project"] = "Neu";
            de["open_project"] = "Oeffnen";
            de["copy"] = "Kopieren";
            de["paste"] = "Einfuegen";
            de["ai_voice"] = "KI STIMME";
            de["ai_frames"] = "KI BILDER";
            de["ai_lyrics"] = "KI SYNCHRONISATION";
            de["ai_transcribe"] = "KI TRANSKRIPTION";
            de["voice_text"] = "Sprechtext:";
            de["lyrics_text"] = "Liedtext:";
            de["select_audio"] = "Audio auswaehlen:";
            de["transcribe_label"] = "Audiodatei:";
            de["transcribe_button"] = "Transkribieren";
            de["generate_voice"] = "Stimme generieren";
            de["generate_frames"] = "Bilder generieren";
            de["sync_lyrics"] = "Text synchronisieren";
            de["add_subtitles"] = "Untertitel hinzufuegen";
            de["video_effects"] = "VIDEO EFFEKTE";
            de["audio_effects"] = "AUDIO EFFEKTE";
            de["brightness"] = "Helligkeit:";
            de["contrast"] = "Kontrast:";
            de["blur"] = "Unschaerfe:";
            de["bass"] = "Bass:";
            de["treble"] = "Hoehen:";
            de["reverb"] = "Hall:";
            de["apply_effects"] = "Effekte anwenden";
            de["subtitle_text"] = "Untertiteltext:";
            de["subtitle_start"] = "Anfang (s):";
            de["subtitle_end"] = "Ende (s):";
            de["add_subtitle"] = "Untertitel hinzufuegen";
            de["clear_subtitles"] = "Alle Untertitel loeschen";
            de["ai_prompt"] = "Bildbeschreibung:";
            de["transitions_tab"] = "UEBERGAENGE";
            de["animation_tab"] = "ANIMATION";
            de["render_cancelled"] = "Rendern abgebrochen";
            _translations["de"] = de;
        }

        public static string GetText(string key, string language = "sr")
        {
            if (_translations.ContainsKey(language) && _translations[language].ContainsKey(key))
                return _translations[language][key];

            if (_translations["en"].ContainsKey(key))
                return _translations["en"][key];

            return key.Replace("_", " ").ToUpper();
        }
    }
}